name: Test dotfiles on macOS

on:
  push:
    branches: [ main, github-action ]
  pull_request:
    branches: [ main ]

jobs:
  test-dotfiles:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set environment variables from zshenv
        shell: zsh {0}
        run: |
          source zsh/zshenv
          echo "XDG_CONFIG_HOME=$XDG_CONFIG_HOME" >> $GITHUB_ENV
          echo "XDG_CACHE_HOME=$XDG_CACHE_HOME" >> $GITHUB_ENV
          echo "XDG_DATA_HOME=$XDG_DATA_HOME" >> $GITHUB_ENV
          echo "XDG_STATE_HOME=$XDG_STATE_HOME" >> $GITHUB_ENV
          echo "ZDOTDIR=$ZDOTDIR" >> $GITHUB_ENV
          echo "VIMINIT=$VIMINIT" >> $GITHUB_ENV

      - name: Run setup script
        shell: zsh {0}
        run: |
          source ~/.zshenv
          chmod +x ./install
          ./install

      - name: Verify shell config
        shell: zsh {0}
        run: |
          test -f "$HOME/.zshenv"
          source ~/.zshenv
          chmod +x .github/workflows/dotfiles-test.sh
          .github/workflows/dotfiles-test.sh
