name: Test dotfiles on macOS

on:
  push:
    branches: [ main, github-action ]
  pull_request:
    branches: [ main ]

jobs:
  test-dotfiles:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run setup script
        run: |
          chmod +x ./install
          ./install

      - name: Verify shell config
        shell: zsh -i {0}
        run: |
          test -f "$HOME/.zshenv"
          source ~/.zshenv
          chmod +x .github/workflows/dotfiles-test.sh
          .github/workflows/dotfiles-test.sh
